### ISSUE TITLE
java.lang.UnsupportedOperationException: This feature requires ASM7

### ISSUE THREAD

**Issue by petarov** [tcurdt/jdependency#21]
Hi,

I'm not familiar with the ins and outs of either `jdependency` or the `asm` projects, but I'm trying to find a fix around an issue in a Gradle plugin called johnrengelman/shadow#406. 

The problem there is that building with OpenJDK 11 does not seem to work due to the following exception:

```java
Caused by: java.lang.UnsupportedOperationException: This feature requires ASM7
        at shadow.org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:150)
        at shadow.org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:153)
        at shadow.org.objectweb.asm.commons.ClassRemapper.visitNestHost(ClassRemapper.java:185)
        at shadow.org.objectweb.asm.ClassReader.accept(ClassReader.java:541)
        at shadow.org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        at shadow.org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:179)
        at shadow.org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:119)
        at shadow.org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:95)
        at shadow.org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:86)
        at shadow.org.vafer.jdependency.Clazzpath$addClazzpathUnit.call(Unknown Source)
        at com.github.jengelman.gradle.plugins.shadow.internal.UnusedTracker$_closure1.doCall(UnusedTracker.groovy:18)

```

I've tested with `jdependency-2.1`, which already uses ASM 7.0-beta, but I think this exception comes from an `Opcodes.ASM6` definition at [DependenciesClassAdapter.java](https://github.com/tcurdt/jdependency/blob/791653bf167d16257ab39dfa30b05983ef8c0daa/src/main/java/org/vafer/jdependency/asm/DependenciesClassAdapter.java#L128) in the `2.1` release.

Does this make sense?

**Comment by cykl** [comment]
Hi @petarov,

I am troubleshooting what seems a related issue but coming from maven-shade-plugin. According to [MSHADE-301](https://issues.apache.org/jira/browse/MSHADE-301) the plugin is expected to support Java 11 (not yet released yet). They upgraded to asm 7.0-beta and use jdependency 2.0.

When the plugin analyse a class containing a static nested class it fails with the following stack trace:

```
Caused by: java.lang.UnsupportedOperationException: This feature requires ASM7
    at org.objectweb.asm.ClassVisitor.visitNestMember (ClassVisitor.java:236)
    at org.objectweb.asm.ClassVisitor.visitNestMember (ClassVisitor.java:239)
    at org.objectweb.asm.commons.ClassRemapper.visitNestMember (ClassRemapper.java:190)
    at org.objectweb.asm.ClassReader.accept (ClassReader.java:651)
    at org.objectweb.asm.ClassReader.accept (ClassReader.java:391)
    at org.vafer.jdependency.Clazzpath.addClazzpathUnit (Clazzpath.java:179)
    at org.vafer.jdependency.Clazzpath.addClazzpathUnit (Clazzpath.java:140)
    at org.apache.maven.plugins.shade.filter.MinijarFilter.<init> (MinijarFilter.java:97)
    at org.apache.maven.plugins.shade.mojo.ShadeMojo.getFilters (ShadeMojo.java:834)
    at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute (ShadeMojo.java:434)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by tcurdt** [comment]
Unfortunately I cannot test JDK11 yet but I have updated the opcodes in master. Tests are still fine.
Would be great if you could report back.

**Comment by cykl** [comment]
Hi @tcurdt,

Thanks for the quick fix. I just tried to plug the latest rev into maven-shade-plugin and my test case is now green, see https://issues.apache.org/jira/browse/MSHADE-302.

I won't be able to test it on real code bases before Monday. Please let me know if you are interested in such feedback.

**Comment by tcurdt** [comment]
@cykl thanks for the quick feedback.

Yes, please let me know. I will then aim for a bug fix release on Mon night or Tue.

**Comment by petarov** [comment]
@tcurdt Thank you for checking this out! Is there a way for you to publish a SNAPSHOT somewhere? It's a bit hard for me to test the jar build locally at the moment.

**Comment by tcurdt** [comment]
@petarov Given I am pretty confident about the fix I could prepare the release. That will create a staging repo and you could use that? Would that work better than just a local `mvn install`?

**Comment by petarov** [comment]
Sound great! I believe that should work for me.

**Comment by tcurdt** [comment]
I didn't realize but Travis has support for jdk11 already. So I expanded the testing matrix.

**Comment by tcurdt** [comment]
Here is the staging repo https://oss.sonatype.org/content/repositories/orgvafer-1026/

**Comment by petarov** [comment]
Amazing, thanks a lot! 👍  Yes, I can confirm this build works on my side and the exception no longer occurs.

**Comment by tcurdt** [comment]
Perfect! I just released it.
Just needs a few minutes to sync to central.

**Comment by GedMarc** [comment]
This fix didn't work for me - I had to manually override the ASM as jdepdency 2.0 points to ASM 6.1

```
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                   <execution>
                       <phase>package</phase>
                       <goals>
                           <goal>shade</goal>
                       </goals>
                   </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.ow2.asm</groupId>
                        <artifactId>asm</artifactId>
                        <version>7.1</version>
                    </dependency>
                    <dependency>
                        <groupId>org.ow2.asm</groupId>
                        <artifactId>asm-util</artifactId>
                        <version>7.1</version>
                    </dependency>
                    <dependency>
                        <groupId>org.ow2.asm</groupId>
                        <artifactId>asm-commons</artifactId>
                        <version>7.1</version>
                    </dependency>
                </dependencies>
            </plugin>
```

**Comment by tcurdt** [comment]
@GedMarc not sure I can follow.

`jdependency-2.2.0` uses `ASM` version 7.1 and even shades it. So the `maven-shade-plugin` should not need to have any dependency on `ASM` at all. Nor should the `jdependency` code care. And overriding would not be possible either as it's not using the `org.ow2.asm` package.

The `maven-shade-plugin` just needs to use the latest version of `jdependency` and done.

**Comment by GedMarc** [comment]
It was jdepedency 2.0, on shade 3.2, and it definitely used asm 6.2 xD
Building on JDK 12, 

I've already resolved it, not really keen on reverting to list the maven dependencies it found for you - took a bit of deep diving to find the dependencies and update them with the solution above,

Perhaps Shade 3.2 hasn't been updated?
Either way, perhaps someone falls into the same thing I did, hopefully it helps them :)

**Comment by tcurdt** [comment]
Well, the ASM upgrade [was done in 2.1](https://github.com/tcurdt/jdependency/blob/master/HISTORY.md)

And the [maven-shade-plugin master](https://github.com/apache/maven-shade-plugin/blob/maven-shade-plugin-3.2.1/pom.xml#L153) has a somewhat recent version.

This really is an issue of the `maven-shade-plugin`.
It needs a release I guess.

> I've already resolved it, not really keen on reverting to list the maven dependencies it found for you - took a bit of deep diving to find the dependencies and update them with the solution above,

Sorry, I am not sure I can follow that sentence.

The better fix is to force an upgrade of the `jdependency` version - not the `ASM` version.
You are just lucky it works with the above change.

**Comment by GedMarc** [comment]
Super Super Weird!!!

I'm going to give the jdepdency change a try, you actually got me to rebuild :) 

Take a peek at these if you can please? I'm not sure what I've setup wrong here, Any assist is greatly appreciated!

[Exception.txt](https://github.com/tcurdt/jdependency/files/3598091/Exception.txt)
[MvnDebug.txt](https://github.com/tcurdt/jdependency/files/3598092/MvnDebug.txt)

**Comment by tcurdt** [comment]
You actually pointed me to an issue with the `mvn-shade-plugin`. It seems relocation is currently not working. Maybe let's move this over to the gitter chat https://gitter.im/tcurdt/jdependency and not abuse this old and closed issue.
