### ISSUE TITLE
A new release for Java 23

### ISSUE THREAD

**Issue by Goooler** [tcurdt/jdependency#294]
Java 23 is out.

https://openjdk.org/projects/jdk/23/

**Comment by tcurdt** [comment]
There are no dependency updates yet and the build matrix passes.
I am not sure what needs to be done for this.

**Comment by Goooler** [comment]
As you shaded ASM for this lib, the bundled one is still lower ASM 9.7, which doesn't support Java 23 yet.

```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 67	
	at org.vafer.jdeb.shaded.objectweb.asm.ClassReader.<init>(ClassReader.java:200)	
	at org.vafer.jdeb.shaded.objectweb.asm.ClassReader.<init>(ClassReader.java:180)	
	at org.vafer.jdeb.shaded.objectweb.asm.ClassReader.<init>(ClassReader.java:166)	
	at org.vafer.jdeb.shaded.objectweb.asm.ClassReader.<init>(ClassReader.java:288)	
	at org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:179)	
	at org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:130)	
	at org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:106)	
	at org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:97)	
	at org.vafer.jdependency.Clazzpath$addClazzpathUnit.call(Unknown Source)	
	at com.github.jengelman.gradle.plugins.shadow.internal.UnusedTracker$_closure1.doCall$original(UnusedTracker.groovy:22)
```

**Comment by Goooler** [comment]
It's #239, which has been merged after [jdependency-2.10](https://github.com/tcurdt/jdependency/releases/tag/jdependency-2.10).

I still suggest we can avoid shading ASM, to get updates easier in consumer sides.

**Comment by tcurdt** [comment]
Ah, somehow forgot to release. Just pushed 2.11 to maven central.

**Comment by Goooler** [comment]
Thanks, it works!
